name: '[Kafka API] CI Tests'

on:
  pull_request:
  push:
    branches:
      - main

env:
  KAFKA_SRC_LINK: https://www.apache.org/dyn/closer.lua/kafka/4.2.0/kafka_2.13-4.2.0.tgz?action=download
  CPU_CORE_NUM:   2
  LIBRDKAFKA_TAG: v2.14.1
  BUILD_SUB_DIR:  builds/sub-build

jobs:
  kafka-api-tests:
    runs-on: ${{ matrix.os }}

    env:
      OS_VERSION:        ${{ matrix.os }}
      BUILD_CXX:         ${{ matrix.build-cxx }}
      BUILD_TYPE:        ${{ matrix.build-type }}
      CXX_STANDARD:      ${{ matrix.cxx-standard }}
      ENABLE_UT_STUBS:   ${{ matrix.enable-ut-stubs }}
      CHECK_OPTION:      ${{ matrix.check-option }}
      GENERATE_DOC:      ${{ matrix.generate-doc }}
      WITH_INSTALLATION: ${{ matrix.with-installation }}
      TEST_LABELS:       ${{ matrix.test-labels }}

    strategy:
      matrix:
        include:
        - os:                macos-26
          build-cxx:         clang++
          build-type:        Debug
          test-labels:       unit|integration
          check-option:      clang-tidy
          enable-ut-stubs:   true

        - os:                macos-26
          build-cxx:         clang++
          build-type:        Release
          test-labels:       robustness

        - os:                ubuntu-24.04
          build-cxx:         g++
          build-type:        Debug
          check-option:      asan,ubsan
          test-labels:       unit|integration
          enable-ut-stubs:   true

        - os:                ubuntu-24.04
          build-cxx:         g++
          check-option:      tsan
          test-labels:       robustness

    steps:
      - uses: actions/checkout@v3

      - name: Preparation
        if: ${{!contains(matrix.os, 'windows')}}
        run: |
          if [[ ${OS_VERSION} == 'ubuntu'* ]]; then
            sed -e 's/azure.archive.ubuntu.com/us.archive.ubuntu.com/g' -e t -e d /etc/apt/sources.list | sudo tee /etc/apt/sources.list.d/nonazure.list
            sudo apt-get update
          elif [[ ${OS_VERSION} == 'macos'* ]]; then
            echo "CPU_CORE_NUM=3" >> $GITHUB_ENV
          fi

      - name: Install Dependencies
        run: |
          mkdir -p ${BUILD_SUB_DIR}
          cd ${BUILD_SUB_DIR}

          # Install clang/clang-tidy
          if [[ ${CHECK_OPTION} == 'clang-tidy' ]]; then
            if [[ ${OS_VERSION} == 'ubuntu'* ]]; then
              sudo apt install -y clang-tidy
            elif [[ ${OS_VERSION} == 'macos'* ]]; then
              brew install llvm
              export PATH=/opt/homebrew/opt/llvm/bin:$PATH
              clang-tidy --version
            fi
          fi

          # Install g++ (newer version), clang
          if [[ ${OS_VERSION} == 'ubuntu-24.04' ]]; then
            if [[ ${BUILD_CXX} == 'g++' ]]; then
              sudo apt install -y gcc-14 g++-14
              sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
              sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
              sudo update-alternatives --set gcc /usr/bin/gcc-14
              sudo update-alternatives --set g++ /usr/bin/g++-14
              g++ --version
            elif [[ ${BUILD_CXX} == 'clang++' ]]; then
              sudo apt install -y clang-20 libc++-20-dev libc++abi-20-dev
              sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-20 100
              sudo update-alternatives --install /usr/bin/clang++ clang++ /usr/bin/clang++-20 100
              clang++ --version
            fi
          fi

          # Install CMake
          if [[ ${OS_VERSION} == 'ubuntu'* ]]; then
              sudo apt install -y cmake
          fi

          # Install googletest
          if [[ ${OS_VERSION} == 'ubuntu'* ]]; then
            sudo apt install -y libgtest-dev
            pushd /usr/src/gtest
            sudo mkdir build
            cd build
            sudo cmake ..
            sudo make
            sudo cp lib/libgtest*.a /usr/lib
            popd
          elif [[ ${OS_VERSION} == 'macos'* ]]; then
            brew install googletest
          fi

          # Install librdkafka
          git clone https://github.com/edenhill/librdkafka.git
          pwd
          cd librdkafka
          git reset --hard ${LIBRDKAFKA_TAG}
          ./configure --cxx=${BUILD_CXX}
          make -j${CPU_CORE_NUM} && sudo make install
          cd ../

          # Install rapidjson (for `addons/KafkaMetrics.h`)
          wget https://github.com/Tencent/rapidjson/archive/refs/heads/master.zip -O rapidjson-master.zip
          unzip rapidjson-master.zip
          sudo cp -r rapidjson-master/include/rapidjson /usr/local/include

          # Install tools to generate document
          if [ ${GENERATE_DOC} ]; then
            sudo apt install -y python3-markdown
            sudo apt install -y doxygen
          fi

          # Install Jre, Kafka for integration/regression tests
          if [[ ${TEST_LABELS} == *'integration'* ]] || [[ ${TEST_LABELS} == *'robustness'* ]]; then
            # Install Jre, lsof
            if [[ ${OS_VERSION} == 'ubuntu'* ]]; then
              sudo apt install -y default-jre
              java -version

              sudo apt install -y lsof
            fi

            # Install kafka
            time wget -nv ${KAFKA_SRC_LINK}
            mkdir -p kafka && tar -xzf `basename ${KAFKA_SRC_LINK}` -C kafka --strip-components=1
            export PATH=`pwd`/kafka/bin:$PATH
          fi

          # Install gtest-parallel for integration test
          if [[ ${TEST_LABELS} == *'integration'* ]]; then
            wget https://github.com/google/gtest-parallel/archive/refs/heads/master.zip
            unzip master.zip
            export PATH=`pwd`/gtest-parallel-master:$PATH
          fi

          # Save the PATH to environment file
          echo "PATH=${PATH}" >> $GITHUB_ENV

          # Print dev env
          cmake --version | head -n 1
          g++ --version | head -n 1
          clang++ --version | head -n 1

      - name: Config
        run: |
          cd ${BUILD_SUB_DIR}

          # Restore the PATH from environment file
          export PATH=${{ env.PATH }}

          if [ ${CXX_STANDARD} ]; then
            export CMAKE_CXX_STANDARD="-DCMAKE_CXX_STANDARD=${CXX_STANDARD}"
          fi

          if [ ${BUILD_TYPE} ]; then
            export CMAKE_BUILD_TYPE="-DCMAKE_BUILD_TYPE=${BUILD_TYPE}"
          else
            export CMAKE_BUILD_TYPE=""
          fi

          if [[ ${ENABLE_UT_STUBS} ]]; then
            export BUILD_OPTION="${BUILD_OPTION} -DBUILD_OPTION_ENABLE_UT_STUBS=ON"
          fi

          if [[ ${CHECK_OPTION} == *'clang-tidy'* ]]; then
            export BUILD_OPTION="${BUILD_OPTION} -DBUILD_OPTION_CLANG_TIDY=ON"
          fi

          if [[ ${CHECK_OPTION} == *'asan'* ]]; then
            export BUILD_OPTION="${BUILD_OPTION} -DBUILD_OPTION_USE_ASAN=ON"
          fi

          if [[ ${CHECK_OPTION} == *'tsan'* ]]; then
            export BUILD_OPTION="${BUILD_OPTION} -DBUILD_OPTION_USE_TSAN=ON"
          fi

          if [[ ${CHECK_OPTION} == *"ubsan"* ]]; then
            export BUILD_OPTION="${BUILD_OPTION} -DBUILD_OPTION_USE_UBSAN=ON"
          fi

          if [ ${GENERATE_DOC} ]; then
            export BUILD_OPTION="${BUILD_OPTION} -DBUILD_OPTION_GEN_DOC=ON"
          fi

          env CXX=${BUILD_CXX} cmake ../.. ${CMAKE_CXX_STANDARD} ${CMAKE_BUILD_TYPE} ${BUILD_OPTION}

      - name: Build
        run: |
          cd ${BUILD_SUB_DIR}

          make -j${CPU_CORE_NUM} VERBOSE=1

      - name: Install
        run: |
          if [ ${WITH_INSTALLATION} ]; then
            cd ${BUILD_SUB_DIR}
            sudo make install
          fi

      - name: Test
        if: matrix.test-labels
        timeout-minutes: 15
        run: |
          cd ${BUILD_SUB_DIR}

          # Restore the PATH from environment file
          export PATH=${{ env.PATH }}

          # Setup Kafka cluster for integration test & regression test
          if [[ ${TEST_LABELS} == *'integration'* ]] || [[ ${TEST_LABELS} == *'robustness'* ]]; then
            # Start Kafka cluster
            rm -f test.env
            ../../scripts/start-local-kafka-cluster.py --controller-port 42181 --broker-ports 40091 40092 40093 &

            # Wait server to be ready
            for i in {1..60}; do cat test.env 2>/dev/null && break || sleep 1; done

            # Set the environment variables: KAFKA_BROKER_LIST, KAFKA_BROKER_PIDS
            source test.env

            cat test.env
            ps aux | grep kafka
          fi

          # Run tests
          ctest -VV -L "${TEST_LABELS}"

          # Stop Kafka cluster for integration test & regression test
          if [[ ${TEST_LABELS} == *'integration'* ]] || [[ ${TEST_LABELS} == *'robustness'* ]]; then
            # Stop Kafka cluster
            kafka-server-stop.sh
          fi

  kafka-api-tests-windows:
    runs-on: windows-latest

    env:
      TEST_LABELS:   ${{ matrix.test-labels }}

    strategy:
      matrix:
        include:
          - test-labels: ''

    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          mkdir -p $Env:BUILD_SUB_DIR
          cd $Env:BUILD_SUB_DIR

          # Install librdkafka
          vcpkg install librdkafka

          # Install googletest
          vcpkg install gtest

          cp -v "C:\VCPKG\INSTALLED\x64-windows\lib\manual-link\gtest_main*" "C:\VCPKG\INSTALLED\x64-windows\lib\"
          cp -v "C:\VCPKG\INSTALLED\x64-windows\lib\manual-link\gtest_main*" "C:\VCPKG\INSTALLED\x64-windows\lib\"

          # Install rapidjson
          vcpkg install rapidjson

          vcpkg integrate install

      - name: Config
        run: |
          cd $Env:BUILD_SUB_DIR

          $Env:GTEST_ROOT='C:\VCPKG\INSTALLED\x64-windows\'
          $Env:LIBRDKAFKA_INCLUDE_DIR='C:\VCPKG\INSTALLED\x64-windows\include\'
          $Env:LIBRDKAFKA_LIBRARY_DIR='C:\VCPKG\INSTALLED\x64-windows\lib\'
          $Env:RAPIDJSON_INCLUDE_DIRS='C:\VCPKG\INSTALLED\x64-windows\include\'

          cmake -B ./ -A x64 -S ../.. "-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake"

      - name: Build
        run: |
          cd $Env:BUILD_SUB_DIR
          cmake --build ./

      - name: Test
        if: matrix.test-labels
        timeout-minutes: 15
        run: |
          cd $Env:BUILD_SUB_DIR
          tree "tests"

          # Install kafka
          Invoke-WebRequest -Uri $Env:KAFKA_SRC_LINK -OutFile kafka_2.13-4.2.0.tgz
          tar xvzf kafka_2.13-4.2.0.tgz

          ctest -VV -L $Env:TEST_LABELS

